namespace Lumper.Generators.FGDGenerator;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

[Generator(LanguageNames.CSharp)]
public sealed class FGDSourceGenerator : IIncrementalGenerator
{
    private const string GeneratedNamespace = "Lumper.Lib.FGD";
    private const string GeneratedClassName = "MomentumFGD";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<FgdFileState> fgdFiles = context
            .AdditionalTextsProvider.Where(static file =>
                Path.GetExtension(file.Path).Equals(".fgd", StringComparison.OrdinalIgnoreCase)
            )
            .Select(
                static (file, ct) =>
                {
                    SourceText? text = file.GetText(ct);
                    if (text == null)
                        return default;

                    return new FgdFileState(file, text.GetChecksum());
                }
            )
            .Where(static state => state.File != null);

        context.RegisterSourceOutput(
            fgdFiles,
            static (spc, state) =>
            {
                SourceText? sourceText = state.File!.GetText(spc.CancellationToken);
                string? content = sourceText?.ToString();

                if (string.IsNullOrEmpty(content))
                {
                    return;
                }

                List<RawEntity> rawEntities = FGDParser.Parse(content!);

                var uniqueTypes = rawEntities
                    .SelectMany(e => e.Properties)
                    .Select(p => p.Type)
                    .Where(t => !string.IsNullOrEmpty(t))
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .OrderBy(t => t)
                    .ToList();

                var lookup = new Dictionary<string, RawEntity>(StringComparer.OrdinalIgnoreCase);
                foreach (RawEntity raw in rawEntities)
                {
                    lookup[raw.Name] = raw;
                }

                var entities = lookup.Values.OrderBy(e => e.Name, StringComparer.OrdinalIgnoreCase).ToList();

                string code = GenerateSource(entities, uniqueTypes);
                spc.AddSource($"{GeneratedClassName}.g.cs", SourceText.From(code, Encoding.UTF8));
            }
        );
    }

    private readonly struct FgdFileState(AdditionalText file, ImmutableArray<byte> checksum) : IEquatable<FgdFileState>
    {
        public AdditionalText? File { get; } = file;
        public ImmutableArray<byte> Checksum { get; } = checksum;

        public bool Equals(FgdFileState other)
        {
            if (File?.Path != other.File?.Path)
                return false;
            if (Checksum.IsDefault && other.Checksum.IsDefault)
                return true;
            if (Checksum.IsDefault || other.Checksum.IsDefault)
                return false;

            return Checksum.SequenceEqual(other.Checksum);
        }

        public override bool Equals(object? obj)
        {
            return obj is FgdFileState other && Equals(other);
        }

        public override int GetHashCode()
        {
            int hash = File?.Path?.GetHashCode() ?? 0;
            if (!Checksum.IsDefault)
            {
                for (int i = 0; i < Math.Min(Checksum.Length, 4); i++)
                {
                    hash = (hash * 31) + Checksum[i];
                }
            }
            return hash;
        }
    }

    private static string GenerateSource(List<RawEntity> entities, List<string> uniqueTypes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by Lumper.Generators/FGDGenerator. Do not edit by hand!");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"namespace {GeneratedNamespace};");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("public enum FGDValueType");
        sb.AppendLine("{");
        sb.AppendLine("    Unknown,");
        foreach (string rawType in uniqueTypes)
        {
            sb.AppendLine($"    {ToSafeIdentifier(rawType)},");
        }
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public static class {GeneratedClassName}");
        sb.AppendLine("{");
        sb.AppendLine(
            "    private static readonly IReadOnlyDictionary<string, FGDEntityRaw> RawEntities = new Dictionary<string, FGDEntityRaw>"
        );
        sb.AppendLine("    {");

        foreach (RawEntity entity in entities)
        {
            AppendDecl(sb, entity);
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine(
            "    public static readonly IReadOnlyDictionary<string, FGDEntity> Entities = FGD.ResolveInheritance(RawEntities);"
        );
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendDecl(StringBuilder sb, RawEntity entity)
    {
        string bases = string.Join(", ", entity.InheritedBases.Select(Lit));

        sb.AppendLine($"        [{Lit(entity.Name)}] = new FGDEntityRaw(");
        sb.AppendLine($"            ClassName: {Lit(entity.Name)},");
        sb.AppendLine($"            ClassType: {Lit(entity.ClassType)},");
        sb.AppendLine($"            Description: {Lit(entity.Description ?? "")},");
        sb.AppendLine($"            Bases: new string[] {{ {bases} }},");

        sb.AppendLine("            Properties: new Dictionary<string, FGDProperty>");
        sb.AppendLine("            {");
        foreach (RawProperty prop in entity.Properties)
        {
            AppendProperty(sb, prop);
        }
        sb.AppendLine("            },");

        sb.AppendLine("            Inputs: new Dictionary<string, FGDInput>");
        sb.AppendLine("            {");
        foreach (RawProperty input in entity.Inputs)
        {
            sb.AppendLine(
                $"                [{Lit(input.Key)}] = new FGDInput({Lit(input.Key)}, {Lit(input.Type)}, {Lit(input.Description ?? "")}),"
            );
        }
        sb.AppendLine("            },");

        sb.AppendLine("            Outputs: new Dictionary<string, FGDOutput>");
        sb.AppendLine("            {");
        foreach (RawProperty output in entity.Outputs)
        {
            sb.AppendLine(
                $"                [{Lit(output.Key)}] = new FGDOutput({Lit(output.Key)}, {Lit(output.Type)}, {Lit(output.Description ?? "")}),"
            );
        }
        sb.AppendLine("            }");

        sb.AppendLine("        ),");
    }

    private static void AppendProperty(StringBuilder sb, RawProperty prop)
    {
        string enumMember = $"FGDValueType.{ToSafeIdentifier(prop.Type)}";

        if (prop.Choices.Count == 0)
        {
            sb.AppendLine(
                $"                [{Lit(prop.Key)}] = new FGDProperty({Lit(prop.Key)}, {enumMember}, "
                    + $"{Lit(prop.DisplayName ?? "")}, {Lit(prop.DefaultValue ?? "")}, {Lit(prop.Description ?? "")}, new Dictionary<string, string>()),"
            );
            return;
        }

        sb.AppendLine(
            $"                [{Lit(prop.Key)}] = new FGDProperty({Lit(prop.Key)}, {enumMember}, "
                + $"{Lit(prop.DisplayName ?? "")}, {Lit(prop.DefaultValue ?? "")}, {Lit(prop.Description ?? "")}, new Dictionary<string, string>"
        );
        sb.AppendLine("                {");
        foreach (KeyValuePair<string, string> choice in prop.Choices)
        {
            sb.AppendLine($"                    [{Lit(choice.Key)}] = {Lit(choice.Value)},");
        }
        sb.AppendLine("                }),");
    }

    private static string ToSafeIdentifier(string rawType)
    {
        if (string.IsNullOrWhiteSpace(rawType))
            return "Unknown";

        string[] parts = rawType.Split(['_', ' ', '-'], StringSplitOptions.RemoveEmptyEntries);
        string pascal = string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p[1..]));

        if (char.IsDigit(pascal[0]))
        {
            pascal = "_" + pascal;
        }

        return pascal;
    }

    private static string Lit(string value)
    {
        return SymbolDisplay.FormatLiteral(value, quote: true);
    }
}
