namespace Lumper.Generators.FGDGenerator;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator(LanguageNames.CSharp)]
public sealed class FGDSourceGenerator : IIncrementalGenerator
{
    private const string GeneratedNamespace = "Lumper.Lib.FGD";
    private const string GeneratedClassName = "MomentumFGD";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<string?> fgdContents = context
            .AdditionalTextsProvider.Where(static file =>
                Path.GetExtension(file.Path).Equals(".fgd", StringComparison.OrdinalIgnoreCase)
            )
            .Select(static (file, ct) => file.GetText(ct)?.ToString());

        context.RegisterSourceOutput(
            fgdContents,
            static (spc, content) =>
            {
                if (string.IsNullOrEmpty(content))
                {
                    return;
                }

                List<RawEntity> rawEntities = FGDParser.Parse(content!);

                var lookup = new Dictionary<string, RawEntity>(StringComparer.OrdinalIgnoreCase);
                foreach (RawEntity raw in rawEntities)
                {
                    lookup[raw.Name] = raw;
                }

                var entities = lookup.Values.OrderBy(e => e.Name, StringComparer.OrdinalIgnoreCase).ToList();

                string code = GenerateSource(entities);
                spc.AddSource($"{GeneratedClassName}.g.cs", SourceText.From(code, Encoding.UTF8));
            }
        );
    }

    private static string GenerateSource(List<RawEntity> entities)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by Lumper.Generators/FGDGenerator. Do not edit by hand!");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"namespace {GeneratedNamespace};");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"public static class {GeneratedClassName}");
        sb.AppendLine("{");
        sb.AppendLine(
            "    private static readonly IReadOnlyDictionary<string, FGDEntityRaw> RawEntities = new Dictionary<string, FGDEntityRaw>"
        );
        sb.AppendLine("    {");

        foreach (RawEntity entity in entities)
        {
            AppendDecl(sb, entity);
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine(
            "    public static readonly IReadOnlyDictionary<string, FGDEntity> Entities = FGD.ResolveInheritance(RawEntities);"
        );
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendDecl(StringBuilder sb, RawEntity entity)
    {
        string bases = string.Join(", ", entity.InheritedBases.Select(Lit));

        sb.AppendLine($"        [{Lit(entity.Name)}] = new FGDEntityRaw(");
        sb.AppendLine($"            ClassName: {Lit(entity.Name)},");
        sb.AppendLine($"            ClassType: {Lit(entity.ClassType)},");
        sb.AppendLine($"            Description: {Lit(entity.Description ?? "")},");
        sb.AppendLine($"            Bases: new string[] {{ {bases} }},");

        sb.AppendLine("            Properties: new Dictionary<string, FGDProperty>");
        sb.AppendLine("            {");
        foreach (RawProperty prop in entity.Properties)
        {
            AppendProperty(sb, prop);
        }
        sb.AppendLine("            },");

        sb.AppendLine("            Inputs: new Dictionary<string, FGDInput>");
        sb.AppendLine("            {");
        foreach (RawProperty input in entity.Inputs)
        {
            sb.AppendLine(
                $"                [{Lit(input.Key)}] = new FGDInput({Lit(input.Key)}, {Lit(input.Type)}, {Lit(input.Description ?? "")}),"
            );
        }
        sb.AppendLine("            },");

        sb.AppendLine("            Outputs: new Dictionary<string, FGDOutput>");
        sb.AppendLine("            {");
        foreach (RawProperty output in entity.Outputs)
        {
            sb.AppendLine(
                $"                [{Lit(output.Key)}] = new FGDOutput({Lit(output.Key)}, {Lit(output.Type)}, {Lit(output.Description ?? "")}),"
            );
        }
        sb.AppendLine("            }");

        sb.AppendLine("        ),");
    }

    private static void AppendProperty(StringBuilder sb, RawProperty prop)
    {
        if (prop.Choices.Count == 0)
        {
            sb.AppendLine(
                $"                [{Lit(prop.Key)}] = new FGDProperty({Lit(prop.Key)}, {Lit(prop.Type)}, "
                    + $"{Lit(prop.DisplayName ?? "")}, {Lit(prop.DefaultValue ?? "")}, {Lit(prop.Description ?? "")}, new Dictionary<string, string>()),"
            );
            return;
        }

        sb.AppendLine(
            $"                [{Lit(prop.Key)}] = new FGDProperty({Lit(prop.Key)}, {Lit(prop.Type)}, "
                + $"{Lit(prop.DisplayName ?? "")}, {Lit(prop.DefaultValue ?? "")}, {Lit(prop.Description ?? "")}, new Dictionary<string, string>"
        );
        sb.AppendLine("                {");
        foreach (KeyValuePair<string, string> choice in prop.Choices)
        {
            sb.AppendLine($"                    [{Lit(choice.Key)}] = {Lit(choice.Value)},");
        }
        sb.AppendLine("                }),");
    }

    private static string Lit(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (char c in value)
        {
            switch (c)
            {
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                default:
                    sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
